# Site settings
title: Muvuca Games
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Criação de jogos em grupo através do IndieDi! :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://muvucagames.github.io" # the base hostname & protocol for your site
twitter_username: diogomrg
github_username:  muvucagames

# Build settings
markdown: kramdown
highlighter: null
paginate: 20